
spring.data.mongodb:
  host: ${MONGODB_HOST:localhost}
  port: ${MONGODB_PORT:27017}
  database: ${MONGODB_DATABASE:desafio}
  username: ${MONGODB_USERNAME:admin}
  password: ${MONGODB_PASSWORD:admin}
