
spring.data.mongodb:
  host: ${MONGODB_HOST:localhost}
  port: ${MONGODB_PORT:27017}
  database: ${MONGODB_DATABASE:desafio}
  username: ${MONGODB_USERNAME:desafio}
  password: ${MONGODB_PASSWORD:desafio}

springdoc.swagger-ui:
    path: /documentation/swagger-ui.html

jwt:
  # Audience:
  #    With the generated token refers to
  #    The application will reject the token if the token received contains
  #    a different token
  audience: ${TOKEN_AUDIENCE:desafio}
  # Time for token expiration in seconds
  time: ${TOKEN_TIME_EXPIRATION:3600}
  #3600
  # String used for signing token
  # At production, please, define other one
  # See more in https://github.com/jwtk/jjwt#secretkey-formats
  # TODO - Change to KeyPair (private/public keys)
  secret: ${TOKEN_SECRET:please_changeme.9JOfm4jC6VrVbZ4f8HiTz6bSes6TYZ6ZA6PqJ2vxet7BtiKwo4B4EmvuxxKy7ck9ogowBWjqrxNv7hE7}

logging:
  level:
    web: DEBUG
    sql: INFO

    org:
      springframework.web: DEBUG
      springframework:
        security: DEBUG
