
spring.data.mongodb:
  host: ${MONGODB_HOST:localhost}
  port: ${MONGODB_PORT:27017}
  database: ${MONGODB_DATABASE:desafio}
  username: ${MONGODB_USERNAME:desafio}
  password: ${MONGODB_PASSWORD:desafio}

springdoc.swagger-ui:
    path: /documentation/swagger-ui.html