version: "3"

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: desafio
      MONGO_INITDB_USER: desafio
      MONGO_INITDB_PWD: desafio
    volumes:
      - ./mongo-init/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
      #- ./data/mongodb/data/db/:/data/db/

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongo:27017/
