@webservice = {{$dotenv WEB_SERVICE}}

@username = {{$dotenv ADMIN_USERNAME}}
@password = {{$dotenv ADMIN_PASSWORD}}

###
# @name auth
POST {{webservice}}/auth
Content-Type: application/x-www-form-urlencoded

username={{username}}
&password={{password}}

###
#
GET {{webservice}}/users/?fullName=rachel&profile=ADMIN HTTP/1.1
Authorization: Bearer {{auth.response.body.id_token}}
content-type: application/json
