@webservice = {{$dotenv WEB_SERVICE}}

###
# Invalid user
POST {{webservice}}/auth
Content-Type: application/x-www-form-urlencoded

username=rachel.queiroz@example.com
&password=StrongP@ssw0rd

###
# Valid user
POST {{webservice}}/auth
Content-Type: application/x-www-form-urlencoded

username=admin@example.com
&password=S3cretP@ssword
